import AnimatedText from "@/components/AnimatedText";
import Layout from "@/components/Layout";
import Skills from "@/components/Skills";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import CountUp from "react-countup";

const statistics = [
  { end: 50, label: "Satisfied Clients" },
  { end: 40, label: "Projects Completed" },
  { end: 4, label: "Years of Experience" },
];

export default function About() {
  return (
    <>
      <Head>
        <title>About Page | Sodiq Ardianto</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex w-full flex-col items-center justify-center">
        <Layout className="pt-36">
          <AnimatedText text="Passion Fuels Purpose!" className="mb-16" />
          <div className="grid w-full grid-cols-8 gap-16">
            <div className="col-span-3 flex flex-col items-start justify-start">
              <h2 className="mb-4 text-lg font-bold uppercase text-dark/75">
                Biography
              </h2>
              <p className="font-medium">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                Tempora quam perferendis consequuntur voluptatem voluptate iusto
                vitae quibusdam odio deleniti aperiam expedita facere minima,
                iure architecto qui, minus sint quos laudantium?
              </p>
              <p className="font-medium my-4">
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae
                nemo iusto labore corrupti ad numquam corporis, placeat dolores
                possimus obcaecati enim aperiam ea doloribus mollitia incidunt
                adipisci. Numquam, alias rerum?
              </p>
              <p className="font-medium">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Harum
                minima natus laboriosam quod, eaque aut dicta saepe blanditiis
                deleniti, inventore temporibus reiciendis, quo eum odio illo ab
                impedit id porro.
              </p>
            </div>
            <div className="col-span-3 relative h-max rounded-2xl border-2 border-solid border-dark bg-light p-8">
              <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark" />
              <Image
                src="/images/developer-pic-2.jpg"
                alt="Photo Profile"
                width={500}
                height={500}
                className="w-full h-auto rounded-2xl"
              />
            </div>
            <div className="col-span-2 flex flex-col items-end justify-between">
              {statistics.map((stat, index) => (
                <div
                  key={index}
                  className="flex flex-col items-end justify-center"
                >
                  <span className="inline-block text-7xl font-bold">
                    <CountUp start={0} end={stat.end} duration={5} /> +
                  </span>
                  <h2 className="text-xl font-medium capitalize text-dark/75">
                    {stat.label}
                  </h2>
                </div>
              ))}
            </div>
          </div>
          <Skills />
        </Layout>
      </main>
    </>
  );
}
