import AnimatedText from "@/components/AnimatedText";
import Education from "@/components/Education";
import Experience from "@/components/Experience";
import Layout from "@/components/Layout";
import Skills from "@/components/Skills";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import CountUp from "react-countup";

const statistics = [
  { end: 50, label: "Satisfied Clients" },
  { end: 40, label: "Projects Completed" },
  { end: 4, label: "Years of Experience" },
];

export default function About() {
  return (
    <>
      <Head>
        <title>About | Sodiq Ardianto</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="w-full flex flex-col items-center justify-center overflow-hidden mb-16 text-dark dark:text-light">
        <Layout className="pt-36">
          <AnimatedText
            text="Passion Fuels Purpose!"
            className="lg:!text-7xl sm:!text-6xl xs:!text-4xl sm:mb-8"
          />
          <div className="grid w-full grid-cols-8 gap-16 my-32 sm:gap-8">
            <div className="col-span-3 flex flex-col items-start justify-start xl:col-span-4 md:order-2 md:col-span-8">
              <h2 className="mb-4 text-lg font-bold uppercase text-dark/75 dark:text-light">
                Biography
              </h2>
              <p className="font-medium">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                Tempora quam perferendis consequuntur voluptatem voluptate iusto
                vitae quibusdam odio deleniti aperiam expedita facere minima,
                iure architecto qui, minus sint quos laudantium?
              </p>
              <p className="font-medium my-4">
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae
                nemo iusto labore corrupti ad numquam corporis, placeat dolores
                possimus obcaecati enim aperiam ea doloribus mollitia incidunt
                adipisci. Numquam, alias rerum?
              </p>
              <p className="font-medium">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Harum
                minima natus laboriosam quod, eaque aut dicta saepe blanditiis
                deleniti, inventore temporibus reiciendis, quo eum odio illo ab
                impedit id porro.
              </p>
            </div>
            <div className="col-span-3 relative h-max rounded-2xl border-2 border-solid border-dark bg-light p-8 dark:bg-dark dark:border-light xl:col-span-4 md:order-1 md:col-span-8">
              <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark rounded-br-3xl dark:bg-light" />
              <Image
                src="/images/developer-pic-2.jpg"
                alt="Photo Profile"
                width={500}
                height={500}
                className="w-full h-auto rounded-2xl"
                priority
                sizes="(min-width: 768px) 100vw,
                (max-width: 1200px)50vw, 33vw"
              />
            </div>
            <div className="col-span-2 flex flex-col items-end justify-between xl:col-span-8 xl:flex-row xl:items-center md:order-3">
              {statistics.map((stat, index) => (
                <div
                  key={index}
                  className="flex flex-col items-end justify-center xl:items-center"
                >
                  <span className="inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl">
                    <CountUp start={0} end={stat.end} duration={5} /> +
                  </span>
                  <h2 className="text-xl font-medium capitalize text-dark/75 dark:text-light/75 xl:text-center md:text-lg sm:text-base xs:text-sm">
                    {stat.label}
                  </h2>
                </div>
              ))}
            </div>
          </div>
          <Skills />
          <Experience />
          <Education />
        </Layout>
      </main>
    </>
  );
}
