import AnimatedText from "@/components/AnimatedText";
import Education from "@/components/Education";
import Experience from "@/components/Experience";
import Layout from "@/components/Layout";
import Skills from "@/components/Skills";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import CountUp from "react-countup";

const statistics = [
  { end: 12, label: "Satisfied Clients" },
  { end: 10, label: "Projects Completed" },
  { end: 3, label: "Years of Experience" },
];

export default function About() {
  return (
    <>
      <Head>
        <title>About | Sodiq Ardianto</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="w-full flex flex-col items-center justify-center overflow-hidden mb-16 text-dark dark:text-light">
        <Layout className="pt-36">
          <AnimatedText
            text="Always learn & develop!"
            className="lg:!text-7xl sm:!text-6xl xs:!text-4xl sm:pt-20"
          />
          <div className="grid w-full grid-cols-8 gap-16 my-32 sm:gap-8 sm:my-16">
            <div className="col-span-3 flex flex-col items-start justify-start xl:col-span-4 md:order-2 md:col-span-8">
              <h2 className="mb-4 text-lg font-bold uppercase text-dark/75 dark:text-light">
                Biography
              </h2>
              <p className="font-medium">
                Hi, I&apos;m Sodiq Ardianto, a Fullstack Developer with 3 years
                of experience and always enthusiastic about learning new things.
                I am a graduate of Raharja University, majoring in Information
                Engineering with a concentration in Software Engineering, and
                graduated in 2020.
              </p>
              <p className="font-medium my-4">
                I am quite proficient in frontend and backend, and have
                successfully completed various projects with the best results.
              </p>
              <p className="font-medium">
                I have the ability to work independently or in a team, and am
                always eager to contribute to the development of useful
                projects. I am confident that I can be a valuable asset to your
                team and ready to build a successful career in technology and
                provide the best solutions for your needs.
              </p>
            </div>
            <div className="col-span-3 relative h-max rounded-2xl border-2 border-solid border-dark bg-light p-8 dark:bg-dark dark:border-light xl:col-span-4 md:order-1 md:col-span-8">
              <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark rounded-br-3xl dark:bg-light" />
              <Image
                src="/images/pic.png"
                alt="Photo Profile"
                width={500}
                height={500}
                className="w-full h-auto rounded-2xl"
                priority
                sizes="(min-width: 768px) 100vw,
                (max-width: 1200px)50vw, 33vw"
              />
            </div>
            <div className="col-span-2 flex flex-col items-end justify-between xl:col-span-8 xl:flex-row xl:items-center md:order-3">
              {statistics.map((stat, index) => (
                <div
                  key={index}
                  className="flex flex-col items-end justify-center xl:items-center"
                >
                  <span className="inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl">
                    <CountUp start={0} end={stat.end} duration={5} /> +
                  </span>
                  <h2 className="text-xl font-medium capitalize text-dark/75 dark:text-light/75 xl:text-center md:text-lg sm:text-base xs:text-sm">
                    {stat.label}
                  </h2>
                </div>
              ))}
            </div>
          </div>
          <Skills />
          <Experience />
          <Education />
        </Layout>
      </main>
    </>
  );
}
