import AnimatedText from "@/components/AnimatedText";
import Layout from "@/components/Layout";
import { motion } from "framer-motion";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";

export default function Articles() {
  return (
    <>
      <Head>
        <title>Articles | Sodiq Ardianto</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="w-full flex flex-col items-center justify-center overflow-hidden mb-16 text-dark dark:text-light">
        <Layout className="pt-36">
          <AnimatedText
            text="No articles have been created yet, please come another time."
            className="lg:!text-7xl sm:!text-6xl xs:!text-4xl sm:mb-8 sm:pt-20"
          />
          {/* <ul className="grid grid-cols-2 gap-16 my-32 md:grid-cols-1 lg:gap-8 md:gap-y-16">
            <li className="col-span-1 w-full p-4 bg-light border border-solid border-dark rounded-2xl relative dark:bg-dark dark:border-light">
              <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark rounded-br-3xl dark:bg-light" />
              <Link
                href={""}
                target="_blank"
                className="w-full inline-block cursor-pointer overflow-hidden rounded-lg"
              >
                <Image
                  src={"/images/articles/pagination component in reactjs.jpg"}
                  width={700}
                  height={700}
                  alt=""
                  className="w-full h-auto hover:scale-110 hover:duration-200"
                  priority
                  sizes="(min-width: 768px) 100vw,
                  (max-width: 1200px)50vw, 33vw"
                />
              </Link>
              <Link href={""} target="_blank">
                <h2 className="capitalize text-2xl font-bold my-2 mt-4 hover:underline xs:text-lg">
                  Build A Custom Pagination Component in ReactJS
                </h2>
              </Link>
              <p className="text-sm mb-2">
                Learn how Lorem ipsum dolor sit amet consectetur adipisicing
                elit. Maiores nemo numquam veritatis reiciendis? Voluptatibus
                alias ducimus qui, sint dolore quas doloribus iure delectus
                aliquam cum sed ipsa ratione explicabo aut!
              </p>
              <span className="text-primary font-semibold dark:text-primaryDark">
                9 min read
              </span>
            </li>
            <li className="col-span-1 w-full p-4 bg-light border border-solid border-dark rounded-2xl relative dark:bg-dark dark:border-light">
              <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark rounded-br-3xl dark:bg-light" />
              <Link
                href={""}
                target="_blank"
                className="w-full inline-block cursor-pointer overflow-hidden rounded-lg"
              >
                <Image
                  src={"/images/articles/pagination component in reactjs.jpg"}
                  width={700}
                  height={700}
                  alt=""
                  className="w-full h-auto hover:scale-110 hover:duration-200"
                  priority
                  sizes="(min-width: 768px) 100vw,
                  (max-width: 1200px)50vw, 33vw"
                />
              </Link>
              <Link href={""} target="_blank">
                <h2 className="capitalize text-2xl font-bold my-2 hover:underline">
                  Build A Custom Pagination Component in ReactJS
                </h2>
              </Link>
              <p className="text-sm mb-2">
                Learn how Lorem ipsum dolor sit amet consectetur adipisicing
                elit. Maiores nemo numquam veritatis reiciendis? Voluptatibus
                alias ducimus qui, sint dolore quas doloribus iure delectus
                aliquam cum sed ipsa ratione explicabo aut!
              </p>
              <span className="text-primary font-semibold dark:text-primaryDark">
                9 min read
              </span>
            </li>
          </ul> */}
          {/* <h2 className="font-bold text-4xl w-full text-center my-16 mt-32">
            All Articles
          </h2>
          <ul>
            <motion.li
              initial={{ y: 200 }}
              whileInView={{
                y: 0,
                transition: { duration: 0.5, ease: "easeInOut" },
              }}
              viewport={{ once: true }}
              className="w-full flex justify-between border border-solid border-dark rounded-xl items-center p-4 py-6 my-4 bg-light text-dark first:mt-0 relative border-r-4 border-b-4 dark:border-light dark:bg-dark dark:text-light sm:flex-col"
            >
              <Link href={""} target="_blank">
                <h2 className="capitalize text-xl font-semibold hover:underline">
                  Form Validation in ReactJS: Build A Reuseable
                </h2>
              </Link>
              <span className="text-primary font-semibold pl4 dark:text-primaryDark sm:self-start sm:pl-0 xs:text-sm">
                March 22, 2023
              </span>
            </motion.li>
            <motion.li
              initial={{ y: 200 }}
              whileInView={{
                y: 0,
                transition: { duration: 0.5, ease: "easeInOut" },
              }}
              viewport={{ once: true }}
              className="w-full flex justify-between border border-solid border-dark rounded-xl items-center p-4 py-6 my-4 bg-light text-dark first:mt-0 relative border-r-4 border-b-4 dark:border-light dark:bg-dark dark:text-light sm:flex-col"
            >
              <Link href={""} target="_blank">
                <h2 className="capitalize text-xl font-semibold hover:underline">
                  Form Validation in ReactJS: Build A Reuseable
                </h2>
              </Link>
              <span className="text-primary font-semibold pl4 dark:text-primaryDark sm:self-start sm:pl-0 xs:text-sm">
                March 22, 2023
              </span>
            </motion.li>
            <motion.li
              initial={{ y: 200 }}
              whileInView={{
                y: 0,
                transition: { duration: 0.5, ease: "easeInOut" },
              }}
              viewport={{ once: true }}
              className="w-full flex justify-between border border-solid border-dark rounded-xl items-center p-4 py-6 my-4 bg-light text-dark first:mt-0 relative border-r-4 border-b-4 dark:border-light dark:bg-dark dark:text-light sm:flex-col"
            >
              <Link href={""} target="_blank">
                <h2 className="capitalize text-xl font-semibold hover:underline">
                  Form Validation in ReactJS: Build A Reuseable
                </h2>
              </Link>
              <span className="text-primary font-semibold pl4 dark:text-primaryDark sm:self-start sm:pl-0 xs:text-sm">
                March 22, 2023
              </span>
            </motion.li>
            <motion.li
              initial={{ y: 200 }}
              whileInView={{
                y: 0,
                transition: { duration: 0.5, ease: "easeInOut" },
              }}
              viewport={{ once: true }}
              className="w-full flex justify-between border border-solid border-dark rounded-xl items-center p-4 py-6 my-4 bg-light text-dark first:mt-0 relative border-r-4 border-b-4 dark:border-light dark:bg-dark dark:text-light sm:flex-col"
            >
              <Link href={""} target="_blank">
                <h2 className="capitalize text-xl font-semibold hover:underline">
                  Form Validation in ReactJS: Build A Reuseable
                </h2>
              </Link>
              <span className="text-primary font-semibold pl4 dark:text-primaryDark sm:self-start sm:pl-0 xs:text-sm">
                March 22, 2023
              </span>
            </motion.li>
          </ul> */}
        </Layout>
      </main>
    </>
  );
}
