import AnimatedText from "@/components/AnimatedText";
import HireMe from "@/components/HireMe";
import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { FaArrowUpRightFromSquare } from "react-icons/fa6";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Sodiq Ardianto</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src="/images/developer-pic-1.png"
                alt="logo"
                width={500}
                height={500}
                className="w-full h-auto"
                priority
                sizes="(min-width: 768px) 100vw,
                (max-width: 1200px)50vw, 33vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code and Design"
                className="!text-6xl !text-left"
              />
              <p className="my-4 text-base font-medium">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Facere
                maiores vel dolores eligendi accusamus modi ullam nihil hic, rem
                ut iste esse, maxime deserunt eaque magnam? Molestias
                exercitationem consequatur dolores!
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href={"/CV Sodiq Ardianto.pdf"}
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:border-light hover:dark:bg-dark hover:dark:text-light"
                  download={true}
                >
                  Resume{" "}
                  <span className="ml-2 text-[18px]">
                    <FaArrowUpRightFromSquare />
                  </span>
                </Link>
                <Link
                  href={"mailto:sodiqardianto@gmail.com"}
                  target="_blank"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
