import AnimatedText from "@/components/AnimatedText";
import HireMe from "@/components/HireMe";
import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { FaArrowUpRightFromSquare } from "react-icons/fa6";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Sodiq Ardianto</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src="/images/pic-1.png"
                alt="Picture of Sodiq"
                width={500}
                height={500}
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(min-width: 768px) 100vw,
                (max-width: 1200px)50vw, 33vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="The only way to do great work is to love what you do."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium">
                As a skilled full-stack developer, I aim to create interactive
                and innovative websites. Explore my latest projects and
                articles, showcasing my web development skills.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href={"/CV Sodiq Ardianto.pdf"}
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:border-light hover:dark:bg-dark hover:dark:text-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume{" "}
                  <span className="ml-2 text-[18px] md:hidden">
                    <FaArrowUpRightFromSquare />
                  </span>
                </Link>
                <Link
                  href={"mailto:sodiqardianto@gmail.com"}
                  target="_blank"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
