import AnimatedText from "@/components/AnimatedText";
import Footer from "@/components/Footer";
import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import { FaGithub } from "react-icons/fa6";

export default function Projects() {
  return (
    <>
      <Head>
        <title>Projects | Sodiq Ardianto</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex w-full flex-col items-center justify-center">
        <Layout className="pt-36">
          <AnimatedText text="Imagination Trumps Knowledge!" className="" />
          <div className="grid grid-cols-12 gap-24 my-32">
            <div className="col-span-12">
              <article className="w-full flex items-center justify-between rounded-3xl border border-solid border-dark bg-light shadow-2xl p-12 rounded-br-2xl relative">
                <div className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2.5rem] bg-dark rounded-br-3xl" />
                <Link
                  href={""}
                  target="_blank"
                  className="w-1/2 cursor-pointer overflow-hidden rounded-lg"
                >
                  <Image
                    src={"/images/projects/crypto-screener-cover-image.jpg"}
                    width={700}
                    height={700}
                    alt=""
                    className="w-full h-auto hover:scale-110 hover:duration-200"
                  />
                </Link>
                <div className="w-1/2 flex flex-col items-start justify-between pl-6">
                  <span className="text-primary font-medium text-xl">
                    Featured Project
                  </span>
                  <Link
                    href={""}
                    target="_blank"
                    className="hover:underline underline-offset-2"
                  >
                    <h2 className="my-2 w-full font-bold text-left text-4xl">
                      Crypto Screnner
                    </h2>
                  </Link>
                  <p className="my-2 font-medium text-dark">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Perspiciatis officia amet incidunt, itaque facere quam
                    inventore facilis molestias maxime illo eaque, deleniti ex
                    necessitatibus. Dolores ratione quod accusamus nobis rem.
                  </p>
                  <div className="mt-2 flex items-center">
                    <Link href={"/"} target="_blank" className="">
                      <FaGithub className="text-4xl" />
                    </Link>
                    <Link
                      href={"/"}
                      target="_blank"
                      className="ml-4 rounded-lg bg-dark text-light p-2 px-6 text-lg font-semibold"
                    >
                      Visit Project
                    </Link>
                  </div>
                </div>
              </article>
            </div>
            <div className="col-span-6">
              <article className="w-full flex flex-col items-center justify-center rounded-2xl border border-solid border-dark bg-light p-6 relative">
                <div className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2rem] bg-dark rounded-br-3xl" />
                <Link
                  href={""}
                  target="_blank"
                  className="w-full cursor-pointer overflow-hidden rounded-lg"
                >
                  <Image
                    src={"/images/projects/crypto-screener-cover-image.jpg"}
                    width={700}
                    height={700}
                    alt=""
                    className="w-full h-auto hover:scale-110 hover:duration-200"
                  />
                </Link>
                <div className="w-full flex flex-col items-start justify-between mt-4">
                  <span className="text-primary font-medium text-xl">
                    Featured Project
                  </span>
                  <Link
                    href={""}
                    target="_blank"
                    className="hover:underline underline-offset-2"
                  >
                    <h2 className="my-2 w-full font-bold text-left text-3xl">
                      Crypto Screnner
                    </h2>
                  </Link>
                  <div className="w-full mt-2 flex items-center justify-between">
                    <Link
                      href={"/"}
                      target="_blank"
                      className="text-lg font-semibold underline"
                    >
                      Visit
                    </Link>
                    <Link href={"/"} target="_blank" className="">
                      <FaGithub className="text-3xl" />
                    </Link>
                  </div>
                </div>
              </article>
            </div>
            <div className="col-span-6">
              <article className="w-full flex flex-col items-center justify-center rounded-2xl border border-solid border-dark bg-light p-6 relative">
                <div className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2rem] bg-dark rounded-br-3xl" />
                <Link
                  href={""}
                  target="_blank"
                  className="w-full cursor-pointer overflow-hidden rounded-lg"
                >
                  <Image
                    src={"/images/projects/crypto-screener-cover-image.jpg"}
                    width={700}
                    height={700}
                    alt=""
                    className="w-full h-auto hover:scale-110 hover:duration-200"
                  />
                </Link>
                <div className="w-full flex flex-col items-start justify-between mt-4">
                  <span className="text-primary font-medium text-xl">
                    Featured Project
                  </span>
                  <Link
                    href={""}
                    target="_blank"
                    className="hover:underline underline-offset-2"
                  >
                    <h2 className="my-2 w-full font-bold text-left text-3xl">
                      Crypto Screnner
                    </h2>
                  </Link>
                  <div className="w-full mt-2 flex items-center justify-between">
                    <Link
                      href={"/"}
                      target="_blank"
                      className="text-lg font-semibold underline"
                    >
                      Visit
                    </Link>
                    <Link href={"/"} target="_blank" className="">
                      <FaGithub className="text-3xl" />
                    </Link>
                  </div>
                </div>
              </article>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
